### ISSUE TITLE
Urban/countryside vs man-made/nature

### ISSUE THREAD

**Issue by puik** [Ajapaik/sift-pics-android#3] opened 2015-11-18 09:32 UTC
On the Sift.pics web app we at some point substituted the categorisation pair "urban/countryside" for "man-made/nature". The reason for that is that without knowing the context it can be hard to decide whether something is from countryside or in a town, while "man-made/nature" should be something that can be decided only by looking at the picture.
So currently this correction is not yet done in the android app's code.

**Comment by puik** [comment] 2015-12-02 10:22
@Abbe98 did you notice this issue?
Do you think you could also make this correction before we publish the app with Swedish and Finnish?
Do you have to know something from backend to make this correction? @Lauriy

**Comment by Abbe98** [comment] 2015-12-02 20:16
Isn't this just about updating the translation files? Or is it tied to backend in some hard coded way?

I would say you publish it and updates it later on.

**Comment by Lauriy** [comment] 2015-12-04 10:10
Hard-coded here:
https://github.com/Ajapaik/sift-pics-android/blob/master/app/src/main/java/pics/sift/app/data/Photo.java

**Comment by Abbe98** [comment] 2016-04-07 09:32
I updated the Photo.java file with the new tag

```
MANMADE_OR_NATURE("manmade_or_nature", 0x04, R.string.photo_tag_manmade, R.drawable.ic_location_city_white_48dp, R.string.photo_tag_nature, R.drawable.ic_nature_white_48dp),
```
&&
```
if(this == INTERIOR_OR_EXTERIOR) {
                return GROUND_OR_RAISED.getMask() | MANMADE_OR_NATURE.getMask();
            }
```

But @puik now says the app does not render the new tagging action or the old one. I have no clue what the hex value in `MANMADE_OR_NATURE` is used for, I'm not sure that even the issue.

**Comment by Abbe98** [comment] 2016-04-07 09:52
The hex value is not the issue I found out after looking into how hex values could be used in Java. The issue is somewhere else. 

I'm afraid I can't test the APK myself currently as my Android device is broken.

**Comment by puik** [comment] 2016-04-07 10:45
I tested the last version too, neither the man-made/nature nor urban/countryside appears...

**Comment by Abbe98** [comment] 2016-04-07 11:34
I find this very wired, I will be able to test it myself on Friday evening
and hopefully figure it out then.

2016-04-07 12:45 GMT+02:00 Vahur Puik <notifications@github.com>:

**Comment by Lauriy** [comment] 2016-04-07 14:37
Backend fixed now.

**Comment by Abbe98** [comment] 2016-04-07 15:01
Thanks Lauri, I had started to guess it was something with the backend but
because it was working correctly on the webpage sending the same tags I
overlooked it.

2016-04-07 16:37 GMT+02:00 Lauri Elias <notifications@github.com>:

**Closed** 2016-04-08 10:26 UTC
